spring.application.name=salon-booking-system
server.port=${PORT:8080}

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL__USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false




app.salon.close-time=20:00
app.salon.name=KATHURA
app.timezone=Asia/Colombo
